name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"

prerelease: true
prerelease-identifier: rc
include-pre-releases: true

categories:
  - title: "📚 Documentation"
    labels:
      - "area/documentation"
  - title: "🚀 New Features"
    labels:
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
  - title: "🚨 Security Updates"
    labels:
      - "security"
  - title: "🔄 Dependency Updates"
    labels:
      - "dependencies"
  - title: "🧑🏼‍💻 Development Tooling"
    labels:
      - "area/dev-tooling"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  $CHANGES

  ## 👨🏼‍💻 Contributors

  $CONTRIBUTORS
autolabeler:
  - label: "area/dev-tooling"
    files:
      - ".github/**/*"
  - label: "area/documentation"
    files:
      - "docs/**/*"
  - label: "maintenance"
    files:
      - "test/**/*"
