name: Update Labels

on:
  workflow_call:

jobs:
  create-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      LABELS_JSON: |
        [
          {"name": "area/documentation", "color": "0075ca", "description": "Improvements or additions to documentation"},
          {"name": "area/dev-tooling", "color": "002A68", "description": "Development Tooling"},
          {"name": "dependencies", "color": "9AF807", "description": "Dependency Updates"},          
          {"name": "major", "color": "11EF57", "description": "Breaking Changes"},
          {"name": "minor", "color": "EAC462", "description": "New Features"},
          {"name": "patch", "color": "B01E00", "description": "Bugfixes"},
          {"name": "stale", "color": "712B19", "description": "It's been a while this has been active"}
        ]
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const labels = JSON.parse(process.env.LABELS_JSON);
          for (const label of labels) {
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                description: label.description || '',
                color: label.color
              });
            } catch (error) {
              // Check if the error is because the label already exists
              if (error.status === 422) {
                console.log(`Label '${label.name}' already exists. Skipping.`);
              } else {
                // Log other errors
                console.error(`Error creating label '${label.name}': ${error}`);
              }
            }
          }
